// app/layout.tsx
import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
// import "../globals.css";
//import { ThemeProvider } from 'next-themes'
//import { ThemeToggle } from "@/components/providers/ThemeToggle"
// import ServiciosMenu from "@/components/menu-tres/ResponsiveMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
       {/* 
       <ThemeProvider 
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
       */} 
        {/*<ServiciosMenu />*/}
           {/*     <div className="flex justify-end mb-4">*/}
        {/*<ThemeToggle />*/}
      {/*</div>*/}
          {children}
          {/*
        </ThemeProvider>
           */}
      </body>
    </html>
  );
}
